name: CI-DEV
on:
  push:
    branches: [dev]
jobs:
  build_and_push_image:
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_LOGIN_GITHUB }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/integrated-int317-int365-announcement/adonis-announcement-project:dev-${{ github.sha }}
