# name: Notify Discord on Push
# on:
#   push:
#     branches:
#       - main

# jobs:
#   notify:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: 16 # ระบุ Node.js เวอร์ชัน 16 ที่นี่

#       - name: Discord notification
#         env:
#           DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
#           DISCORD_USERNAME: ASAP BOT
#           DISCORD_AVATAR: https://resize.programme-television.ladmedia.fr/r/670,670/img/var/premiere/storage/images/tele-7-jours/news-tv/oss-117-le-caire-nid-d-espions-c8-le-show-de-jean-dujardin-4484285/90175763-1-fre-FR/OSS-117-Le-Caire-nid-d-espions-C8-Le-show-de-Jean-Dujardin.jpg
#         uses: Ilshidur/action-discord@master
#         with:
#           args: 'A new commit has been pushed to Ilshidur/action-discord.'

#       - name: Discord notification
#         env:
#           DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
#         uses: Ilshidur/action-discord@master
